version: "3"

services:
  node:
    container_name: node
    image: node
    user: "1000:1000"
    working_dir: /usr/share/app
    ports:
      - 8080:8080
    volumes:
      - ./node-app:/usr/share/app
    # command: '-e "setInterval(() => console.log(''Running Container''), 1000)"'
    command: ["node", "src/index.js"]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
